"use client";

import { memo, useEffect, useMemo, useRef, useState } from "react";
import type { GeoProjection } from "d3-geo";
import { TransformComponent, TransformWrapper, type ReactZoomPanPinchRef } from "react-zoom-pan-pinch";
import countriesTopology from "world-atlas/countries-110m.json";
import { places } from "@/content/places";
import { WIDTH, HEIGHT, buildMapGeometry, desertRegions, regionPath } from "./baseMap";
import styles from "./WorldMap.module.css";

// The pre-rendered base map, generated by scripts/generate-base-map.mjs.
const BASE_MAP_SRC = "/map-base.webp";

// At or above this zoom, when the map is at rest, we render the crisp vector
// base instead of the bitmap: only a small slice of the map is on screen so the
// paint is cheap, and it stays sharp. Below it (or mid-gesture) we use the
// bitmap so panning/zooming and big reveals stay perfectly smooth.
const VECTOR_ZOOM = 2;

// Only cull off-screen markers once there are enough of them to matter; below
// this the whole set renders (no pop-in, identical to before).
const CULL_THRESHOLD = 120;

type Bounds = { minX: number; maxX: number; minY: number; maxY: number };

// One small cluster of overlapping glyphs marks each major forest / mountain,
// placed at a single representative coordinate per feature.
const forestMarks = [
  { name: "Amazon rainforest", coordinate: [-62, -4] as [number, number] },
  { name: "Congo rainforest", coordinate: [22, -1] as [number, number] },
  { name: "North American boreal forest", coordinate: [-103, 57] as [number, number] },
  { name: "Eurasian taiga", coordinate: [96, 62] as [number, number] },
  { name: "Southeast Asian forest", coordinate: [107, 2] as [number, number] },
  { name: "European forest", coordinate: [26, 54] as [number, number] },
];

const mountainMarks = [
  { name: "Rocky Mountains", coordinate: [-114, 44] as [number, number] },
  { name: "Patagonia", coordinate: [-71, -46] as [number, number] },
  { name: "Himalayas", coordinate: [84, 30] as [number, number] },
  { name: "Atlas Mountains", coordinate: [-3, 32] as [number, number] },
  { name: "East African Highlands", coordinate: [37, 0] as [number, number] },
];

const PINE = "M0 -8 L-4 1 H-1.5 L-4.6 5 H4.6 L1.5 1 H4 Z M-0.9 5 H0.9 V7.5 H-0.9 Z";

// A sparse scattering of ships and whales gives the open oceans some life.
const shipMarks = [
  { name: "North Pacific sail", coordinate: [-150, 22] as [number, number] },
  { name: "South Pacific sail", coordinate: [-128, -18] as [number, number] },
  { name: "North Atlantic sail", coordinate: [-34, 34] as [number, number] },
  { name: "South Atlantic sail", coordinate: [-24, -34] as [number, number] },
  { name: "Indian sail", coordinate: [78, -22] as [number, number] },
  { name: "Coral Sea sail", coordinate: [162, -18] as [number, number] },
  { name: "Japan sail", coordinate: [155, 19] as [number, number] },
];

const whaleMarks = [
  { name: "Pacific whale", coordinate: [-158, 36] as [number, number], flip: false },
  { name: "Atlantic whale", coordinate: [-20, -6] as [number, number], flip: true },
];

// A few recognisable landmark silhouettes, kept well away from the photo markers.
const landmarkMarks = [
  { name: "Pyramids of Giza", kind: "pyramids", coordinate: [31, 29.5] as [number, number] },
  { name: "Christ the Redeemer", kind: "christ", coordinate: [-43.2, -22.9] as [number, number] },
  { name: "Taj Mahal", kind: "taj", coordinate: [78, 27] as [number, number] },
  { name: "Sydney Opera House", kind: "sydney", coordinate: [151.2, -33.85] as [number, number] },
  { name: "Statue of Liberty", kind: "liberty", coordinate: [-74, 40.7] as [number, number] },
  { name: "Tokyo Tower", kind: "tokyo", coordinate: [139.7, 35.7] as [number, number] },
] as const;

const oceanLabels = [
  { label: "Pacific Ocean", coordinates: [-148, 5] as [number, number] },
  { label: "Atlantic Ocean", coordinates: [-32, 3] as [number, number] },
  { label: "Indian Ocean", coordinates: [78, -20] as [number, number] },
];

export function WorldMap({ markerTarget = "page" }: { markerTarget?: "page" | "section" }) {
  const [zoomScale, setZoomScale] = useState(1);
  // The element the map fills. All sizing (cover factor, initial view, marker
  // culling) is measured from THIS container, not the window, so the map works
  // windowed in a pane exactly as it did full-screen — no empty band, correct
  // pan bounds. `sizeRef` holds the latest measured size for use in callbacks.
  const rootRef = useRef<HTMLDivElement>(null);
  const sizeRef = useRef({ w: 0, h: 0 });
  // True while a pan/pinch/zoom gesture is in progress. Used to promote the map
  // to a GPU layer and suppress the costly SVG filters during the gesture only.
  const [interacting, setInteracting] = useState(false);
  // Timestamp of the last time we synced zoomScale into React state. The map
  // itself scales smoothly via the library's DOM transform every frame; we only
  // need to re-render the SVG (markers counter-scale, terrain fade/thresholds)
  // occasionally during a gesture, then exactly once it ends. Re-rendering on
  // every frame is what made drastic pinches feel jumpy.
  const lastZoomSync = useRef(0);
  // The static base map (ocean, land, borders, deserts, graticule) is a single
  // pre-rendered bitmap served from /map-base.webp. Panning/zooming it is just
  // texture sampling — no vector paint when a fresh region scrolls in, which is
  // what made moving into un-rendered areas feel jumpy. If it ever fails to
  // load we fall back to drawing the base as vector.
  const [baseImageOk, setBaseImageOk] = useState(true);
  // The viewBox rectangle currently on screen (plus a generous margin), so that
  // when there are many markers we only render the ones near the viewport. null
  // means "render all" (the zoomed-out / initial state). Recomputed only when a
  // gesture ends, never mid-gesture, so it never adds re-renders while panning.
  const [visibleBounds, setVisibleBounds] = useState<Bounds | null>(null);

  // Map a transform (content px offset + scale) to the viewBox rectangle it
  // shows, expanded by 75% each side so markers are ready before they scroll in.
  const computeVisibleBounds = (posX: number, posY: number, scale: number): Bounds | null => {
    const { w, h } = sizeRef.current;
    if (!w || !h) return null;
    const cover = Math.max(w / WIDTH, h / HEIGHT);
    const unit = cover * scale; // content px per viewBox unit
    const spanX = w / unit;
    const spanY = h / unit;
    const minX = -posX / unit;
    const minY = -posY / unit;
    const mx = spanX * 0.75;
    const my = spanY * 0.75;
    return { minX: minX - mx, maxX: minX + spanX + mx, minY: minY - my, maxY: minY + spanY + my };
  };

  // Filters are suppressed while a gesture is in progress and restored when it
  // ends — toggled on gesture start/stop (before movement begins), which is the
  // stable approach. There's no momentum, so "gesture end" is when motion stops.
  const startGesture = () => setInteracting(true);
  const endGesture = (ref: ReactZoomPanPinchRef) => {
    setInteracting(false);
    setZoomScale(ref.state.scale);
    applyTerrainFade(ref.state.scale);
    if (places.length > CULL_THRESHOLD) {
      setVisibleBounds(computeVisibleBounds(ref.state.positionX, ref.state.positionY, ref.state.scale));
    }
  };

  // The terrain-icon group is rendered once and never re-rendered on zoom; its
  // fade is applied imperatively (no React) so zooming through the mid-range
  // doesn't reconcile/mount the icon clusters each frame.
  const terrainRef = useRef<SVGGElement>(null);
  const applyTerrainFade = (scale: number) => {
    const g = terrainRef.current;
    if (!g) return;
    g.style.opacity = String(Math.max(0, Math.min(1, (4 - scale) / 2)));
  };

  const handleTransform = (state: { scale: number }) => {
    applyTerrainFade(state.scale); // every frame, no re-render — smooth fade
    // Throttle the zoom-driven re-render (marker sizing) to ~10fps while moving;
    // the exact final scale is applied by endGesture.
    const now = performance.now();
    if (now - lastZoomSync.current >= 100) {
      lastZoomSync.current = now;
      setZoomScale(state.scale);
    }
  };
  // null until mounted so we can size the map to the device first. `cover` is
  // the factor that makes the map (at its true aspect) exactly cover the
  // viewport. We render the SVG at cover size so the pannable content IS the
  // map rectangle — panning is then clamped to the map's edges and can never
  // reveal empty space (Google-Maps style), with no aspect-ratio bands.
  const [view, setView] = useState<{ mobile: boolean; cover: number; reducedMotion: boolean } | null>(null);

  useEffect(() => {
    const el = rootRef.current;
    if (!el) return;
    const reduce = window.matchMedia("(prefers-reduced-motion: reduce)");
    const compute = () => {
      const w = el.clientWidth;
      const h = el.clientHeight;
      if (!w || !h) return;
      sizeRef.current = { w, h };
      setView({
        mobile: window.matchMedia("(max-width: 720px)").matches,
        cover: Math.max(w / WIDTH, h / HEIGHT),
        reducedMotion: reduce.matches,
      });
    };
    compute();
    const observer = new ResizeObserver(compute);
    observer.observe(el);
    reduce.addEventListener("change", compute);
    return () => {
      observer.disconnect();
      reduce.removeEventListener("change", compute);
    };
  }, []);
  const { landPath, antarcticaPath, greenlandPath, bordersPath, graticulePath, projection } = useMemo(
    () => buildMapGeometry(countriesTopology),
    [],
  );

  // Project a coordinate and round it, so the SSR and client renders produce
  // identical transforms (Mercator's Math.log/tan can differ by ~1e-13 between
  // the Node and browser runtimes, which otherwise trips a hydration mismatch).
  const project = (coordinate: [number, number]): [number, number] | null => {
    const point = projection(coordinate);
    if (!point) return null;
    return [Math.round(point[0] * 1000) / 1000, Math.round(point[1] * 1000) / 1000];
  };

  // Set the opening view: the whole world centred on desktop, zoomed into
  // Europe on mobile. The content is the cover-sized map rectangle, so
  // 1 viewBox unit = `cover` content px. Computed from the window (which equals
  // the full-screen viewport) so it matches the rendered SVG size exactly.
  const setInitialView = (api: ReactZoomPanPinchRef) => {
    if (typeof window === "undefined") return;
    requestAnimationFrame(() => {
      const { w, h } = sizeRef.current;
      if (!w || !h) return;
      if (!window.matchMedia("(max-width: 720px)").matches) {
        api.centerView(1, 0);
        setVisibleBounds(null); // whole world visible at scale 1
        applyTerrainFade(1);
        return;
      }
      const cover = Math.max(w / WIDTH, h / HEIGHT);
      const europe = projection([9, 49]);
      if (!europe) return;
      const scale = 2.6;
      // Clamp to the map bounds so centring Europe never exposes empty space.
      const clamp = (v: number, min: number) => Math.min(0, Math.max(min, v));
      const px = clamp(w / 2 - europe[0] * cover * scale, w - WIDTH * cover * scale);
      const py = clamp(h / 2 - europe[1] * cover * scale, h - HEIGHT * cover * scale);
      api.setTransform(px, py, scale, 0);
      setVisibleBounds(computeVisibleBounds(px, py, scale));
      applyTerrainFade(scale);
    });
  };

  // Before we know the container size, show a plain ocean placeholder so the map
  // mounts exactly once at the correct size. The .root wrapper is always present
  // (both states) so the ResizeObserver can measure it.
  if (view === null) {
    return (
      <div ref={rootRef} className={styles.root}>
        <div className={styles.viewport} aria-hidden="true" />
      </div>
    );
  }

  const { mobile: isMobile, cover, reducedMotion } = view;
  const contentWidth = WIDTH * cover;
  const contentHeight = HEIGHT * cover;
  // Honour the OS "reduce motion" setting: no zoom easing, no pan inertia.
  const animTime = reducedMotion ? 0 : 300;
  const shouldCull = places.length > CULL_THRESHOLD;

  // Bitmap only when zoomed OUT (where it's displayed small and cheap); crisp
  // vector when zoomed in. Showing the bitmap while zoomed in is catastrophic —
  // it gets scaled to tens of thousands of px and the map's CSS filter must
  // re-rasterise that whole surface every frame.
  const showBitmapBase = baseImageOk && zoomScale < VECTOR_ZOOM;

  return (
    <div ref={rootRef} className={styles.root}>
    <TransformWrapper
      key={isMobile ? "mobile" : "desktop"}
      initialScale={isMobile ? 1.8 : 1}
      minScale={1}
      maxScale={12}
      centerZoomedOut
      limitToBounds
      smooth={false}
      wheel={{ step: 0.055, disabled: false }}
      pinch={{ disabled: false, step: 5 }}
      keyboard={{ disabled: false, zoomStep: 0.35, panStep: 60 }}
      doubleClick={{ disabled: false, step: 0.7, mode: "zoomIn", animationTime: animTime, animationType: "easeOutQuad" }}
      panning={{ velocityDisabled: true }}
      onInit={setInitialView}
      onTransform={(_, state) => handleTransform(state)}
      onPanningStart={startGesture}
      onPanningStop={endGesture}
      onPinchStart={startGesture}
      onPinchStop={endGesture}
      onZoomStart={startGesture}
      onZoomStop={endGesture}
      onWheelStart={startGesture}
      onWheelStop={endGesture}
    >
      {({ zoomIn, zoomOut, resetTransform }) => (
        <>
          <TransformComponent
            wrapperClass={styles.viewport}
            contentClass={`${styles.canvas}${interacting ? " " + styles.interacting : ""}`}
            contentStyle={{ width: contentWidth, height: contentHeight }}
          >
            <svg
              className={styles.map}
              viewBox={`0 0 ${WIDTH} ${HEIGHT}`}
              preserveAspectRatio="xMidYMid meet"
              role="group"
              aria-label="Illustrated travel map. Decorative; the markers below link to places with photographs."
            >
              <defs>
                <pattern id="waves" width="34" height="18" patternUnits="userSpaceOnUse">
                  <path d="M0 10 Q8 4 17 10 T34 10" fill="none" stroke="#89ab9d" strokeWidth="1" opacity=".27" />
                </pattern>
                <radialGradient id="warm-sea" cx="50%" cy="40%" r="78%">
                  <stop offset="0%" stopColor="#f3e8c9" stopOpacity="0.34" />
                  <stop offset="55%" stopColor="#e9dcbc" stopOpacity="0.13" />
                  <stop offset="100%" stopColor="#c8b78c" stopOpacity="0" />
                </radialGradient>
                <filter id="paper-noise">
                  <feTurbulence type="fractalNoise" baseFrequency="0.72" numOctaves="2" seed="8" result="noise" />
                  <feBlend in="SourceGraphic" in2="noise" mode="multiply" />
                </filter>
                <filter id="soft-shadow" x="-30%" y="-30%" width="160%" height="160%">
                  <feDropShadow dx="0" dy="3" stdDeviation="3" floodColor="#203128" floodOpacity=".24" />
                </filter>
                <filter id="terrain-soft" x="-8%" y="-8%" width="116%" height="116%">
                  <feGaussianBlur stdDeviation="3.5" />
                </filter>
                <clipPath id="land-clip"><path d={landPath} /></clipPath>
                <pattern id="land-speckle" width="18" height="18" patternUnits="userSpaceOnUse">
                  <circle cx="3" cy="5" r=".7" fill="#536f4e" opacity=".22" />
                  <circle cx="14" cy="12" r=".5" fill="#f4edd7" opacity=".38" />
                  <path d="M7 16 l3 -1" stroke="#667e59" strokeWidth=".45" opacity=".22" />
                </pattern>
              </defs>

              {showBitmapBase ? (
                // Bitmap while zoomed out: pans/zooms are texture sampling, so
                // revealing a fresh region never triggers a paint.
                <image
                  href={BASE_MAP_SRC}
                  x={0}
                  y={0}
                  width={WIDTH}
                  height={HEIGHT}
                  preserveAspectRatio="none"
                  aria-hidden="true"
                  onError={() => setBaseImageOk(false)}
                />
              ) : (
                // Crisp vector base: shown at rest when zoomed in (only a small
                // slice is visible, so it's cheap), and as the instant fallback
                // before the bitmap has finished rasterising.
                <>
                  <rect width={WIDTH} height={HEIGHT} fill="#c6dbcf" />
                  <rect width={WIDTH} height={HEIGHT} fill="url(#waves)" />
                  <rect width={WIDTH} height={HEIGHT} fill="url(#warm-sea)" />
                  <path className={styles.graticule} d={graticulePath} />
                  <path className={styles.landShadow} d={antarcticaPath} transform="translate(0 5)" />
                  <path className={styles.iceLand} d={antarcticaPath} />
                  <path className={styles.landShadow} d={landPath} transform="translate(0 5)" />
                  <path className={styles.land} d={landPath} />
                  <path className={styles.landTexture} d={landPath} fill="url(#land-speckle)" />
                  <path className={styles.iceLand} d={greenlandPath} />

                  <g className={styles.terrain} clipPath="url(#land-clip)" aria-hidden="true">
                    {desertRegions.map((region) => (
                      <path key={region.name} className={styles.desert} d={regionPath(projection, region)}><title>{region.name}</title></path>
                    ))}
                  </g>

                  <path className={styles.borders} d={bordersPath} />
                </>
              )}

              {/* Rendered once; faded/hidden imperatively via terrainRef in
                  applyTerrainFade so zooming never re-renders these clusters. */}
              <g ref={terrainRef} className={styles.terrainFill} aria-hidden="true">
                <TerrainIcons projection={projection} />
              </g>

              <g aria-hidden="true">
                {oceanLabels.map((ocean) => {
                  const point = project(ocean.coordinates);
                  if (!point) return null;
                  return <text key={ocean.label} className={styles.oceanLabel} x={point[0]} y={point[1]} textAnchor="middle">{ocean.label}</text>;
                })}
              </g>

              {places.map((place) => {
                const point = project(place.coordinates);
                if (!point) return null;
                // When there are many markers, skip ones well outside the view.
                if (
                  shouldCull &&
                  visibleBounds &&
                  (point[0] < visibleBounds.minX ||
                    point[0] > visibleBounds.maxX ||
                    point[1] < visibleBounds.minY ||
                    point[1] > visibleBounds.maxY)
                ) {
                  return null;
                }
                return (
                  <PlaceMarker key={place.slug} slug={place.slug} name={place.name} x={point[0]} y={point[1]} zoomScale={zoomScale} markerTarget={markerTarget} />
                );
              })}

            </svg>
          </TransformComponent>

          <div className={styles.controls} aria-label="Map zoom controls">
            <button type="button" onClick={() => zoomIn(0.4, animTime, "easeOutQuad")} aria-label="Zoom in">+</button>
            <button type="button" onClick={() => zoomOut(0.4, animTime, "easeOutQuad")} aria-label="Zoom out">−</button>
            <button type="button" onClick={() => resetTransform()} aria-label="Reset map">↺</button>
          </div>
        </>
      )}
    </TransformWrapper>
    </div>
  );
}

// All the decorative terrain/ocean icons, memoised on the (stable) projection
// so this whole subtree renders exactly once. Its fade in/out with zoom is
// applied imperatively by the parent (see applyTerrainFade), never via a
// re-render, so panning/zooming through the mid-range stays smooth.
const TerrainIcons = memo(function TerrainIcons({ projection }: { projection: GeoProjection }) {
  const project = (coordinate: [number, number]): [number, number] | null => {
    const point = projection(coordinate);
    if (!point) return null;
    return [Math.round(point[0] * 1000) / 1000, Math.round(point[1] * 1000) / 1000];
  };
  return (
    <>
      {forestMarks.map((mark) => {
        const point = project(mark.coordinate);
        return point ? <ForestCluster key={mark.name} x={point[0]} y={point[1]} name={mark.name} /> : null;
      })}
      {mountainMarks.map((mark) => {
        const point = project(mark.coordinate);
        return point ? <MountainCluster key={mark.name} x={point[0]} y={point[1]} name={mark.name} /> : null;
      })}
      {shipMarks.map((mark) => {
        const point = project(mark.coordinate);
        return point ? <Ship key={mark.name} x={point[0]} y={point[1]} name={mark.name} /> : null;
      })}
      {whaleMarks.map((mark) => {
        const point = project(mark.coordinate);
        return point ? <Whale key={mark.name} x={point[0]} y={point[1]} flip={mark.flip} name={mark.name} /> : null;
      })}
      {landmarkMarks.map((mark) => {
        const point = project(mark.coordinate);
        return point ? <Landmark key={mark.name} kind={mark.kind} x={point[0]} y={point[1]} name={mark.name} /> : null;
      })}
    </>
  );
});

// A single location pin, memoised so that (with many markers) React only
// reconciles the ones whose props actually change. `scale(1 / zoomScale)` keeps
// the pin a constant on-screen size as the map zooms.
const PlaceMarker = memo(function PlaceMarker({
  slug,
  name,
  x,
  y,
  zoomScale,
  markerTarget,
}: {
  slug: string;
  name: string;
  x: number;
  y: number;
  zoomScale: number;
  markerTarget: "page" | "section";
}) {
  const showLabel = zoomScale >= 5;
  const section = markerTarget === "section";
  const href = section ? `#place-${slug}` : `/places/${slug}`;
  return (
    <g transform={`translate(${x} ${y})`}>
      <a
        className={styles.marker}
        href={href}
        aria-label={section ? `Jump to ${name}` : `Open photographs from ${name}`}
        onClick={
          section
            ? (event) => {
                // preventDefault so the URL hash doesn't jump instantly; scroll
                // smoothly instead (honours CSS scroll-behavior + reduced-motion).
                event.preventDefault();
                document.getElementById(`place-${slug}`)?.scrollIntoView();
              }
            : undefined
        }
      >
        <title>{name}</title>
        <g transform={`scale(${1 / zoomScale})`}>
          <circle className={styles.markerHit} r="12" />
          {!showLabel && <circle className={styles.markerDot} r="3" />}
          {showLabel && (
            <g className={styles.markerLabel} transform="scale(0.5)">
              <path d="M0 -13 C-7.5 -13 -13 -7.5 -13 0 C-13 9 0 21 0 21 C0 21 13 9 13 0 C13 -7.5 7.5 -13 0 -13Z" />
              <circle cx="0" cy="0" r="3.5" />
            </g>
          )}
        </g>
      </a>
    </g>
  );
});

// One mountain peak (flat lit face, shadow side, snow cap). Several of these
// overlap to form a single compact range icon.
function Peak({ dx, dy, h, w }: { dx: number; dy: number; h: number; w: number }) {
  return (
    <g transform={`translate(${dx} ${dy})`}>
      <path className={styles.mountainFace} d={`M${-w} 5 Q${-w * 0.42} ${-h * 0.16} 0 ${-h} Q${w * 0.42} ${-h * 0.16} ${w} 5 Z`} />
      <path className={styles.mountainShadow} d={`M0 ${-h} Q${w * 0.42} ${-h * 0.16} ${w} 5 L${w * 0.14} 5 Z`} />
      <path className={styles.mountainSnow} d={`M${-h * 0.17} ${-h * 0.54} Q${-h * 0.05} ${-h * 0.5} 0 ${-h} Q${h * 0.07} ${-h * 0.52} ${h * 0.2} ${-h * 0.52} L${h * 0.05} ${-h * 0.64} L${-h * 0.06} ${-h * 0.58} Z`} />
    </g>
  );
}

// A single icon for a mountain range: 5 overlapping peaks, tallest in the
// middle, drawn back-to-front so nearer peaks sit in front.
const MOUNTAIN_PEAKS = [
  { dx: -15, dy: 5, h: 12, w: 8 },
  { dx: -7, dy: 2, h: 19, w: 12 },
  { dx: 2, dy: 0, h: 25, w: 15 },
  { dx: 11, dy: 3, h: 17, w: 11 },
  { dx: 18, dy: 6, h: 12, w: 8 },
].sort((a, b) => a.dy - b.dy);

function MountainCluster({ x, y, name }: { x: number; y: number; name: string }) {
  return (
    <g className={styles.mountainIcon} transform={`translate(${x} ${y}) scale(0.66)`} aria-label={name}>
      <title>{name}</title>
      {MOUNTAIN_PEAKS.map((peak, index) => (
        <Peak key={index} {...peak} />
      ))}
    </g>
  );
}

// A single icon for a forest: 5 overlapping pine trees forming a small grove.
const FOREST_TREES = [
  { dx: -12, dy: 4, s: 0.82 },
  { dx: -6, dy: 1, s: 1 },
  { dx: 0, dy: 5, s: 1.12 },
  { dx: 6, dy: 1, s: 1 },
  { dx: 12, dy: 4, s: 0.82 },
].sort((a, b) => a.dy - b.dy);

function ForestCluster({ x, y, name }: { x: number; y: number; name: string }) {
  return (
    <g className={styles.forestIcon} transform={`translate(${x} ${y})`} aria-label={name}>
      <title>{name}</title>
      {FOREST_TREES.map((tree, index) => (
        <path key={index} transform={`translate(${tree.dx} ${tree.dy}) scale(${tree.s})`} d={PINE} />
      ))}
    </g>
  );
}

// A little sailing boat for the open ocean.
function Ship({ x, y, name }: { x: number; y: number; name: string }) {
  return (
    <g className={styles.oceanIcon} transform={`translate(${x} ${y}) scale(1.15)`} aria-label={name}>
      <title>{name}</title>
      <path className={styles.shipMast} d="M0.4 -10 V1" />
      <path className={styles.shipSail} d="M1.2 -9.5 L1.2 0 L7.5 0 Z" />
      <path className={styles.shipSail} d="M-0.4 -6 L-0.4 0 L-5 0 Z" />
      <path className={styles.shipHull} d="M-6.5 0.5 Q0 5 7 0.5 L5 4 Q0 5.4 -4.5 4 Z" />
    </g>
  );
}

// A simple breaching whale with a spout.
function Whale({ x, y, flip, name }: { x: number; y: number; flip: boolean; name: string }) {
  return (
    <g className={styles.oceanIcon} transform={`translate(${x} ${y}) scale(${flip ? -0.66 : 0.66} 0.66)`} aria-label={name}>
      <title>{name}</title>
      <path
        className={styles.whale}
        d="M-11 1 C-11 -4 -5 -6 1 -5 C6 -4 8 -2 9 0 C10 -3 12 -3 12 -1 C12 0 11 1 10 1 C12 2 12 4 11 5 C10 5 9 3 9 1 C8 3 6 4 1 4 C-5 5 -11 4 -11 1 Z"
      />
      <circle className={styles.whaleEye} cx="-7" cy="-1.4" r="0.75" />
      <path className={styles.whaleSpout} d="M-9 -5.5 Q-10.5 -9.5 -8.5 -12 M-9 -5.5 Q-8 -9.5 -6 -11" />
    </g>
  );
}

// Recognisable landmark silhouettes, one per iconic place, coloured to match
// the real material of each monument.
const LANDMARK_CLASS: Record<string, string> = {
  pyramids: styles.lmSand,
  christ: styles.lmConcrete,
  taj: styles.lmMarble,
  sydney: styles.lmMarble,
  liberty: styles.lmPatina,
  tokyo: styles.lmTowerRed,
};

function Landmark({ kind, x, y, name }: { kind: string; x: number; y: number; name: string }) {
  return (
    <g className={`${styles.landmark} ${LANDMARK_CLASS[kind]}`} transform={`translate(${x} ${y}) scale(0.95)`} aria-label={name}>
      <title>{name}</title>
      {kind === "pyramids" && (
        <>
          <path d="M-2 6 L12 6 L5 -6 Z" />
          <path className={styles.lmSandShade} d="M5 -6 L12 6 L5.5 6 Z" />
          <path d="M-12 6 L2 6 L-5 -9 Z" />
          <path className={styles.lmSandShade} d="M-5 -9 L2 6 L-4.2 6 Z" />
        </>
      )}
      {kind === "christ" && (
        <>
          <path className={styles.lmStone} d="M-3.4 4.5 L3.4 4.5 L2.4 8 L-2.4 8 Z" />
          <rect x="-0.85" y="-7" width="1.7" height="11.5" />
          <path d="M-6 -4.4 L6 -4.4 L6 -3 L-6 -3 Z" />
          <circle cx="0" cy="-8.4" r="1.35" />
        </>
      )}
      {kind === "taj" && (
        <>
          <path className={styles.lmMarbleShade} d="M-8.8 -4 h1.7 v9 h-1.7 Z" />
          <path className={styles.lmMarbleShade} d="M7.1 -4 h1.7 v9 h-1.7 Z" />
          <circle cx="-7.95" cy="-4.4" r="1.15" />
          <circle cx="7.95" cy="-4.4" r="1.15" />
          <path d="M-5.5 5 v-8 h11 v8 Z" />
          <path d="M-3.8 -3 Q-4.3 -9.6 0 -12 Q4.3 -9.6 3.8 -3 Z" />
          <rect x="-0.45" y="-14.4" width="0.9" height="2.6" />
        </>
      )}
      {kind === "sydney" && (
        <>
          <path className={styles.lmStone} d="M-10 5 h20 v1.6 h-20 Z" />
          <path d="M-9.5 5 Q-9 -4.5 -3.2 5 Z" />
          <path className={styles.lmMarbleShade} d="M-6.4 5 Q-5.6 -6.5 1.2 5 Z" />
          <path d="M-2.6 5 Q-1.6 -6 4.8 5 Z" />
          <path className={styles.lmMarbleShade} d="M2 5 Q5.6 -3.5 9.4 5 Z" />
        </>
      )}
      {kind === "liberty" && (
        <>
          <path className={styles.lmStone} d="M-3.4 4.5 L3.4 4.5 L2.8 8 L-2.8 8 Z" />
          <path d="M-2.4 5 L2.4 5 L1.5 -5.4 L-1.5 -5.4 Z" />
          <circle cx="0" cy="-6.8" r="1.35" />
          <path className={styles.lmPatinaStroke} d="M-2.2 -8 L-1.5 -6.7 M-1.1 -8.6 L-0.7 -7.1 M0 -8.9 L0 -7.3 M1.1 -8.6 L0.7 -7.1 M2.2 -8 L1.5 -6.7" />
          <path className={styles.lmPatinaArm} d="M1.4 -3.4 L4.2 -9" />
          <circle className={styles.lmFlame} cx="4.5" cy="-9.9" r="1.15" />
        </>
      )}
      {kind === "tokyo" && (
        <>
          {/* antenna mast */}
          <path d="M-0.45 -11 L-0.2 -17 L0.2 -17 L0.45 -11 Z" />
          {/* upper tapered section */}
          <path d="M-2.6 -1.6 Q-1.4 -6.5 -0.55 -11 L0.55 -11 Q1.4 -6.5 2.6 -1.6 Z" />
          {/* main observation deck */}
          <path d="M-3.8 -2.4 L3.8 -2.4 L3.3 -0.3 L-3.3 -0.3 Z" />
          {/* splayed lattice legs with an arch between them */}
          <path d="M-3.3 -0.5 Q-4.8 2.6 -6.4 6 L-3.7 6 Q-1.9 2.4 -0.8 -0.5 Z" />
          <path d="M3.3 -0.5 Q4.8 2.6 6.4 6 L3.7 6 Q1.9 2.4 0.8 -0.5 Z" />
          {/* leg cross-bracing */}
          <path className={styles.lmTowerLattice} d="M-5.6 4 L-2.9 4 M2.9 4 L5.6 4 M-4.7 1.9 L-2.3 1.9 M2.3 1.9 L4.7 1.9" />
          {/* alternating white bands */}
          <path className={styles.lmTowerWhite} d="M-2.15 -4.4 L2.15 -4.4 L2.45 -2.7 L-2.45 -2.7 Z" />
          <path className={styles.lmTowerWhite} d="M-1.15 -8.5 L1.15 -8.5 L1.45 -6.9 L-1.45 -6.9 Z" />
        </>
      )}
    </g>
  );
}
