// Scans public/images/places/<slug>/ and writes src/content/photos.generated.ts,
// a plain-data manifest of every place's photos. Run via `npm run generate:photos`
// (also runs automatically before `npm run dev` and `npm run build`).
//
// Convention: drop image files into public/images/places/<place-slug>/.
// Filenames can be anything and are NOT exposed anywhere — only the folder's
// <place-slug> (the headline place) is used for labels, so a specific
// sub-location is never leaked. Portrait or landscape both work; photos are
// interleaved by orientation (portrait-led) so a run of landscapes never leads
// and the home preview (first few) shows a combination.

import sharp from "sharp";
import { readdirSync, statSync, writeFileSync, existsSync } from "node:fs";
import { join, parse } from "node:path";

const ROOT = process.cwd();
const PLACES_DIR = join(ROOT, "public", "images", "places");
const OUT_FILE = join(ROOT, "src", "content", "photos.generated.ts");
const IMAGE_EXT = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif"]);

// Only the folder slug labels a photo — never the filename.
function slugLabel(slug) {
  return slug.replace(/[-_]+/g, " ").trim().toLowerCase();
}

// Alternate two lists (portrait first), then any leftovers — so orientations
// mix rather than clumping.
function interleave(portrait, landscape) {
  const out = [];
  const max = Math.max(portrait.length, landscape.length);
  for (let i = 0; i < max; i += 1) {
    if (i < portrait.length) out.push(portrait[i]);
    if (i < landscape.length) out.push(landscape[i]);
  }
  return out;
}

const manifest = {};

if (existsSync(PLACES_DIR)) {
  const slugs = readdirSync(PLACES_DIR).filter((entry) =>
    statSync(join(PLACES_DIR, entry)).isDirectory(),
  );

  for (const slug of slugs.sort()) {
    const dir = join(PLACES_DIR, slug);
    const files = readdirSync(dir)
      .filter((file) => IMAGE_EXT.has(parse(file).ext.toLowerCase()))
      .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

    if (files.length === 0) continue;

    const label = slugLabel(slug);
    const portrait = [];
    const landscape = [];

    for (const file of files) {
      const meta = await sharp(join(dir, file)).metadata();
      const width = meta.width ?? 0;
      const height = meta.height ?? 0;
      const isLandscape = width >= height;
      const photo = {
        id: parse(file).name,
        src: `/images/places/${slug}/${file}`,
        alt: label,
        caption: label,
        orientation: isLandscape ? "landscape" : "portrait",
        // height ÷ width, so the preview can skip odd (very tall/narrow) shots.
        ratio: width ? Math.round((height / width) * 100) / 100 : 1,
      };
      (isLandscape ? landscape : portrait).push(photo);
    }

    manifest[slug] = interleave(portrait, landscape);
  }
}

const body = `// AUTO-GENERATED by scripts/generate-photos.mjs — do not edit by hand.
// Run \`npm run generate:photos\` after adding or removing photos.

export type GeneratedPhoto = { id: string; src: string; alt: string; caption: string; orientation: "portrait" | "landscape"; ratio: number };

export const GENERATED_PHOTOS: Record<string, GeneratedPhoto[]> = ${JSON.stringify(manifest, null, 2)};
`;

writeFileSync(OUT_FILE, body);

const total = Object.values(manifest).reduce((sum, list) => sum + list.length, 0);
console.log(`generate:photos → ${Object.keys(manifest).length} places, ${total} photos`);
